make dotmgr more comprehensive
dotmgr now just has two non-bootstrap subcommands and has a more
friendly menu for choosing a particular action. The descriptions
of a particular command incorrectly wraps around this interface
and will be fixed in a later release

diff --git a/bootstrap/dotmgr/bin/dotmgr b/bootstrap/dotmgr/bin/dotmgr
--- a/bootstrap/dotmgr/bin/dotmgr
+++ b/bootstrap/dotmgr/bin/dotmgr
@@ -1,32 +1,11 @@
 #!/usr/bin/env bash
-set -eo pipefail
-shopt -s dotglob nullglob shift_verbose
 
-DOTMGR_ROOT_DIR="${0%/*}"; DOTMGR_ROOT_DIR="${DOTMGR_ROOT_DIR%/*}"
-source "$DOTMGR_ROOT_DIR/lib/util.sh"
+if ((EUID == 0)); then
+	printf '%s\n' "Error: Cannot run 'dotmgr' as root" >&2
+	exit 1
+fi
 
-main() {
-	if ((EUID == 0)); then
-		util.die "Cannot run as root"
-	fi
+DOTMGR_ROOT_DIR=${0%/*}; DOTMGR_ROOT_DIR=${DOTMGR_ROOT_DIR%/*}
 
-	for arg; do case "$arg" in
-	-h|--help)
-		util.show_help
-		exit
-		;;
-	esac done
-
-	local subcommand="$1"
-	if [ -f "$DOTMGR_ROOT_DIR/lib/commands/$subcommand.sh" ]; then
-		shift
-		source "$DOTMGR_ROOT_DIR/lib/commands/$subcommand.sh" "$@"
-		subcmd "$@"
-	else
-		util.show_help
-		util.log_error "No matching subcommand found"
-		exit 1
-	fi
-}
-
-main "$@"
+source "$DOTMGR_ROOT_DIR/src/bin/dotmgr.sh"
+main.dotmgr "$@"
