chore: Improve dotfile boostrapping

diff --git a/bootstrap/dotmgr/bin/dotmgr b/bootstrap/dotmgr/bin/dotmgr
--- a/bootstrap/dotmgr/bin/dotmgr
+++ b/bootstrap/dotmgr/bin/dotmgr
@@ -1,50 +1,36 @@
 #!/usr/bin/env bash
 set -eo pipefail
+shopt -s nullglob
 
-ROOT_DIR="$HOME/.dots/bootstrap/dotmgr"
+DOTMGR_ROOT_DIR="${0%/*}"; DOTMGR_ROOT_DIR="${DOTMGR_ROOT_DIR%/*}"
+source "$DOTMGR_ROOT_DIR/lib/util.sh"
 
-source "$ROOT_DIR/lib/util.sh"
+main() {
+	trap sigint INT
+	sigint() {
+		die 'Received SIGINT'
+	}
 
-trap sigint INT
-sigint() {
-	die 'Received SIGINT'
+	if ((EUID == 0)); then
+		die "Cannot run as root"
+	fi
+
+	for arg; do case "$arg" in
+	-h|--help)
+		util.show_help
+		exit
+		;;
+	esac done
+
+	local subcommand="$1"
+	if [ -f "$DOTMGR_ROOT_DIR/lib/commands/$subcommand.sh" ]; then
+		shift
+		source "$DOTMGR_ROOT_DIR/lib/commands/$subcommand.sh" "$@"
+	else
+		log_error "No matching subcommand found"
+		util.show_help
+		exit 1
+	fi
 }
 
-if ((EUID == 0)); then
-	die "Cannot run as root"
-fi
-
-for arg; do case "$arg" in
--h|--help)
-	util.show_help
-	exit
-	;;
-esac done
-
-case "$1" in
-bootstrap)
-	shift
-	source "$ROOT_DIR/lib/commands/bootstrap.sh"
-	;;
-module)
-	shift
-	source "$ROOT_DIR/lib/commands/module.sh"
-	;;
-module-show)
-	shift
-	source "$ROOT_DIR/lib/commands/module-show.sh"
-	;;
-maintain)
-	shift
-	source "$ROOT_DIR/lib/commands/maintain.sh"
-	;;
-import-gpgkey)
-	shift
-	source "$ROOT_DIR/lib/commands/import-gpgkey.sh"
-	;;
-*)
-	log_error "No matching subcommand found"
-	util.show_help
-	exit 1
-	;;
-esac
+main "$@"
